import React, { createContext, useContext, useState, useEffect } from "react";

const translations = {
  fr: {
    // Navigation
    "nav.dashboard": "Tableau de bord",
    "nav.bandes": "Bandes",
    "nav.provenderie": "Provenderie",
    "nav.medicaments": "Médicaments",
    "nav.equipes": "Équipes",
    "nav.comptabilite": "Comptabilité",
    "nav.fournisseurs": "Fournisseurs",
    "nav.clients": "Clients",
    "nav.boutique": "Ma Boutique",
    "nav.assistant": "Mon Assistant",
    "nav.parametres": "Paramètres",
    "nav.logout": "Déconnexion",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "nav.more": "Plus",
    "nav.home": "Accueil",
    // Dashboard
    "dashboard.title": "Tableau de bord",
    "dashboard.description": "Vue d'ensemble de votre exploitation avicole",
    "dashboard.period": "Période des statistiques financières",
    "dashboard.display": "Affichage",
    "dashboard.revenues": "Revenus",
    "dashboard.expenses": "Dépenses",
    "dashboard.balance": "Solde net",
    "dashboard.mortality": "Mortalité totale",
    "dashboard.activeBands": "Bandes actives",
    "dashboard.subjects": "sujets",
    // Common
    "common.add": "Ajouter",
    "common.edit": "Modifier",
    "common.delete": "Supprimer",
    "common.cancel": "Annuler",
    "common.save": "Enregistrer",
    "common.search": "Rechercher",
    "common.loading": "Chargement...",
    "common.allMonths": "Tous les mois",
    "common.noData": "Aucune donnée",
    "common.today": "Aujourd'hui",
    "common.yesterday": "Hier",
    "common.daysAgo": "Il y a {n} jours",
    "common.kg": "kg",
    // Bandes
    "bandes.title": "Mes Bandes",
    "bandes.newBande": "Nouvelle bande",
    "bandes.descOne": "{n} bande active",
    "bandes.descMany": "{n} bandes actives",
    "bandes.totalActive": "Total bandes actives",
    "bandes.monthMortality": "Mortalité totale ce mois",
    "bandes.monthFeedCost": "Coût provende total ce mois",
    "bandes.all": "Toutes",
    "bandes.active": "En cours",
    "bandes.sold": "Vendues",
    "bandes.planned": "Planifiées",
    "bandes.totalPlural": "{n} bandes au total",
    "bandes.totalSingular": "{n} bande au total",
    "bandes.empty.title": "Aucune bande",
    "bandes.empty.desc": "Commencez par ajouter votre première bande de volaille",
    "bandes.empty.action": "Ajouter une bande",
    // Provenderie
    "provenderie.title": "Provenderie",
    "provenderie.descOne": "{n} aliment en stock",
    "provenderie.descMany": "{n} aliments en stock",
    "provenderie.newFood": "Nouvel aliment",
    "provenderie.totalValue": "Valeur stock total (FCFA)",
    "provenderie.lowAlerts": "Alertes stock bas",
    "provenderie.monthConsumption": "Consommation ce mois (kg)",
    "provenderie.search": "Rechercher par nom...",
    "provenderie.filter.all": "Tous",
    "provenderie.filter.stock": "En stock",
    "provenderie.filter.alert": "Alerte",
    "provenderie.filter.archived": "Archivés",
    "provenderie.empty.title": "Aucun aliment en stock",
    "provenderie.empty.desc": "Ajoutez vos aliments pour suivre les stocks et la consommation",
    "provenderie.empty.action": "Ajouter un aliment",
    "provenderie.history.title": "Historique",
    "provenderie.history.empty": "Aucune consommation enregistrée",
    // Settings
    "settings.title": "Paramètres",
    "settings.description": "Gérez votre profil et vos préférences de compte",
    "settings.language": "Langue de l'application",
    "settings.languageDesc": "Choisissez la langue d'affichage de l'interface",
    "settings.french": "Français",
    "settings.english": "English",
    "settings.profile": "Informations personnelles",
    "settings.profileDesc": "Votre nom et coordonnées",
    "settings.fullName": "Nom complet",
    "settings.fullNamePlaceholder": "Votre nom complet",
    "settings.phone": "Numéro de téléphone",
    "settings.email": "Adresse email",
    "settings.emailNote": "L'email ne peut pas être modifié.",
    "settings.saveChanges": "Enregistrer les modifications",
    "settings.saving": "Enregistrement...",
    "settings.saved": "Enregistré",
    "settings.password": "Changer le mot de passe",
    "settings.passwordDesc": "Mettez à jour votre mot de passe de connexion",
    "settings.newPassword": "Nouveau mot de passe",
    "settings.confirmPassword": "Confirmer le nouveau mot de passe",
    "settings.changePassword": "Changer le mot de passe",
    "settings.changing": "Modification...",
    "settings.account": "Mon compte",
    "settings.accountDesc": "Informations et actions sur votre compte",
    "settings.memberSince": "Membre depuis",
    "settings.role": "Rôle",
    "settings.admin": "Administrateur",
    "settings.user": "Utilisateur",
    "settings.adminDesc": "Administrateur de l'application",
    "settings.userDesc": "Utilisateur standard",
    "settings.logout": "Se déconnecter",
    "settings.active": "Actif",
    "settings.genericError": "Erreur lors du changement de mot de passe.",
    "settings.toastTitle": "Profil mis à jour",
    "settings.toastDesc": "Vos informations ont été enregistrées.",
    "settings.pwToastTitle": "Mot de passe modifié",
    "settings.pwToastDesc": "Votre mot de passe a été mis à jour avec succès.",
    "settings.pwMismatch": "Les mots de passe ne correspondent pas.",
    "settings.pwTooShort": "Le nouveau mot de passe doit contenir au moins 6 caractères.",
    "settings.pwPlaceholder": "Minimum 6 caractères",
    "settings.deleteAccount": "Supprimer mon compte",
    "settings.deleteConfirmTitle": "Supprimer définitivement votre compte ?",
    "settings.deleteConfirmDesc": "⚠️ Avertissement : La suppression de votre compte effacera définitivement toutes vos données, registres, fichiers, paramètres et historique de la plateforme. Cette action est irréversible. Voulez-vous vraiment continuer ?",
    "settings.deleteBackupNote": "💡 Avant de continuer, vous pouvez exporter une sauvegarde de vos données depuis les pages Bandes et Comptabilité.",
    "settings.deleteAcknowledgeLabel": "Je comprends que cette action est définitive et irréversible.",
    "settings.deleteConfirmButton": "Oui, supprimer mon compte",
    "settings.deleteEmailSubject": "Demande de suppression de compte AgriVolaille",
    "settings.deleteEmailBody": "Une demande de suppression du compte associé à l'adresse {email} a été soumise. Votre compte et toutes les données associées seront supprimés sous peu.",
    "settings.deleteSubmittedTitle": "Demande envoyée",
    "settings.deleteSubmittedDesc": "Votre demande de suppression a été enregistrée. Vous allez être déconnecté.",
    // Common additional
    "common.update": "Mettre à jour",
    "common.create": "Créer",
    "common.nameRequired": "Nom *",
    "common.phone": "Téléphone",
    "common.address": "Adresse",
    "common.notes": "Notes",
    // Equipes
    "equipes.title": "Équipes",
    "equipes.description": "Gérez vos employés et suivez la masse salariale",
    "equipes.newEmploye": "Nouvel employé",
    "equipes.activeEmployees": "Employés actifs",
    "equipes.payrollPerMonth": "Masse salariale / mois",
    "equipes.inactiveOrLeave": "Inactifs / congé",
    "equipes.empty.title": "Aucun employé",
    "equipes.empty.desc": "Ajoutez vos employés pour suivre votre équipe et la masse salariale",
    "equipes.empty.action": "Ajouter un employé",
    // Fournisseurs
    "fournisseurs.title": "Fournisseurs",
    "fournisseurs.descOne": "{n} fournisseur",
    "fournisseurs.descMany": "{n} fournisseurs",
    "fournisseurs.newSupplier": "Nouveau fournisseur",
    "fournisseurs.search": "Rechercher...",
    "fournisseurs.empty.title": "Aucun fournisseur",
    "fournisseurs.empty.desc": "Ajoutez vos fournisseurs pour les retrouver facilement",
    "fournisseurs.empty.action": "Ajouter",
    "fournisseurs.menu.edit": "Modifier",
    "fournisseurs.menu.delete": "Supprimer",
    "fournisseurs.form.editTitle": "Modifier le fournisseur",
    "fournisseurs.form.newTitle": "Nouveau fournisseur",
    // Clients
    "clients.title": "Clients",
    "clients.descOne": "{n} client",
    "clients.descMany": "{n} clients",
    "clients.newClient": "Nouveau client",
    "clients.search": "Rechercher...",
    "clients.empty.title": "Aucun client",
    "clients.empty.desc": "Ajoutez vos clients pour les retrouver facilement",
    "clients.empty.action": "Ajouter",
    "clients.menu.edit": "Modifier",
    "clients.menu.delete": "Supprimer",
    "clients.form.editTitle": "Modifier le client",
    "clients.form.newTitle": "Nouveau client",
    // Common additional
    "common.revenus": "Revenus",
    "common.depenses": "Dépenses",
    "common.balanceShort": "Solde",
    "common.viewAll": "Voir tout",
    "common.noTransaction": "Aucune transaction",
    "common.noActiveBands": "Aucune bande active",
    "common.noFeedRecorded": "Aucun aliment enregistré",
    // Charts
    "dashboard.charts.headerTitle": "Revenus vs Dépenses",
    "dashboard.charts.lastMonths": "{n} derniers mois",
    "dashboard.charts.balance": "Solde",
    "dashboard.charts.monthsN": "{n} mois",
    "dashboard.charts.expByCat": "Dépenses par catégorie",
    "dashboard.charts.revByCat": "Revenus par catégorie",
    "dashboard.charts.top5": "Top 5 dépenses du mois",
    "dashboard.charts.noExpense": "Aucune dépense ce mois",
    "dashboard.recentTx": "Transactions récentes",
    "dashboard.activeBandsHeading": "Bandes actives",
    "dashboard.stockAlerts": "Alertes stock",
    "dashboard.kgRemaining": "{actual} kg restants (seuil: {threshold} kg)",
    "dashboard.allStocksOk": "Tous les stocks sont OK",
    // Period filter
    "periodFilter.mode": "Mode période",
    "periodFilter.singleMonth": "Mois unique",
    "periodFilter.range": "Plage personnalisée",
    "periodFilter.month": "Mois",
    "periodFilter.from": "De",
    "periodFilter.to": "À",
    "periodFilter.startMonthPlaceholder": "Mois de début",
    "periodFilter.endMonthPlaceholder": "Mois de fin",
    // Species
    "espece.poulet_chair": "Poulet de chair",
    "espece.pondeuse": "Pondeuse",
    "espece.pintade": "Pintade",
    "espece.canard": "Canard",
    "espece.dinde": "Dinde",
    "espece.caille": "Caille",
    // Categories
    "cat.vente_volaille": "Vente volaille",
    "cat.vente_oeufs": "Vente œufs",
    "cat.vente_fumier": "Vente fumier",
    "cat.achat_aliment": "Achat aliment",
    "cat.achat_poussins": "Achat poussins",
    "cat.medicaments": "Médicaments",
    "cat.main_oeuvre": "Main d'œuvre",
    "cat.equipement": "Équipement",
    "cat.transport": "Transport",
    "cat.electricite_eau": "Élec./Eau",
    "cat.autre": "Autre",
    // Medicaments
    "medicaments.title": "Médicaments & Santé",
    "medicaments.description": "Gérez vos stocks sanitaires et l'historique des traitements",
    "medicaments.newMedicament": "Nouveau médicament",
    "medicaments.inStock": "Produits en stock",
    "medicaments.lowStockAlerts": "Alertes stock bas",
    "medicaments.upcomingReminders": "Rappels à venir",
    "medicaments.tabs.stock": "Stock médicaments",
    "medicaments.tabs.history": "Historique traitements",
    "medicaments.tabs.calendar": "📅 Calendrier",
    "medicaments.tabs.archived": "Archivés",
    "medicaments.empty.title": "Aucun médicament",
    "medicaments.empty.desc": "Ajoutez vos médicaments et vaccins pour suivre les stocks et traitements",
    "medicaments.empty.action": "Ajouter un médicament",
    "medicaments.archive.empty": "Aucun médicament archivé",
    "medicaments.unknownMed": "Médicament inconnu",
    "medicaments.reminders.empty": "Aucun rappel à venir",
    "medicaments.reminders.emptyDesc": "Ajoutez un traitement avec une date de rappel pour le voir ici",
    "medicaments.reminders.add": "Ajouter un rappel",
    "medicaments.selectBande": "Sélectionner une bande",
    "medicaments.daysLeftOne": "Dans {n} jour",
    "medicaments.daysLeftMany": "Dans {n} jours",
    // Comptabilite
    "comptabilite.title": "Comptabilité",
    "comptabilite.exercice": "Exercice {period}",
    "comptabilite.excel": "Excel",
    "comptabilite.csv": "CSV",
    "comptabilite.pdfReport": "Rapport PDF",
    "comptabilite.newTransaction": "Nouvelle transaction",
    "comptabilite.revenues": "Revenus de la période",
    "comptabilite.expenses": "Dépenses de la période",
    "comptabilite.netBalance": "Solde net",
    "comptabilite.txCount": "Nombre de transactions",
    "comptabilite.filter.type": "Type",
    "comptabilite.filter.category": "Catégorie",
    "comptabilite.filter.band": "Bande",
    "comptabilite.filter.search": "Recherche",
    "comptabilite.filter.searchPlaceholder": "Mots clés...",
    "comptabilite.filter.allTypes": "Tous",
    "comptabilite.filter.income": "Revenus",
    "comptabilite.filter.expense": "Dépenses",
    "comptabilite.filter.allCategories": "Toutes",
    "comptabilite.filter.allBands": "Toutes les bandes",
    "comptabilite.empty.title": "Aucune transaction",
    "comptabilite.empty.desc": "Enregistrez vos revenus et dépenses pour voir les données",
    "comptabilite.empty.action": "Ajouter une transaction",
    "common.heads": "têtes",
    "common.add": "Ajouter",
    // Bande detail page
    "bandeDetail.title": "Détail de la bande",
    "bandeDetail.notFound": "Bande introuvable",
    "bandeDetail.backToFlocks": "Retour aux bandes",
    "bandeDetail.strain": "Souche",
    "bandeDetail.strainUndefined": "Non définie",
    "bandeDetail.species": "Espèce",
    "bandeDetail.statusActive": "En cours",
    "bandeDetail.statusCompleted": "Terminée",
    "bandeDetail.statusPlanned": "Planifiée",
    "bandeDetail.headsCurInit": "Têtes actuelles / initiales",
    "bandeDetail.deaths": "{n} morts",
    "bandeDetail.totalMortality": "Mortalité totale",
    "bandeDetail.totalFeedCost": "Coût provende total",
    "bandeDetail.costPerHead": "Coût de production / tête",
    "bandeDetail.rearingDuration": "Durée en élevage",
    "bandeDetail.days": "{n} jours",
    "bandeDetail.growthCurveTitle": "Courbe de croissance",
    "bandeDetail.slaughterBadge": "Abattage J42",
    "bandeDetail.noRealRecord": "0 relevé réel",
    "bandeDetail.slaughterLabel": "Abattage",
    "bandeDetail.reference": "Référence",
    "bandeDetail.real": "Réel",
    "bandeDetail.icTarget": "IC cible: 1.8 - 2.2",
    "bandeDetail.mortalityTarget": "Mortalité cible: < 3%",
    "bandeDetail.startLabel": "Départ: {date}",
    "bandeDetail.daysAxis": "Jours / Days",
    "bandeDetail.tabOverview": "Aperçu",
    "bandeDetail.tabHealth": "Santé",
    "bandeDetail.tabMortality": "Mortalité",
    "bandeDetail.tabFeed": "Provende",
    "bandeDetail.tabProfitability": "Rentabilité",
    "bandeDetail.infoSection": "Informations bande",
    "bandeDetail.entryDate": "Date d'entrée",
    "bandeDetail.avgEntryWeight": "Poids moyen à l'entrée",
    "bandeDetail.lastHealthFollowups": "Derniers suivis santé",
    "bandeDetail.noFollowup": "Aucun suivi.",
    "bandeDetail.registerMortality": "🔴 Enregistrer mortalité",
    "bandeDetail.addHealthFollowup": "🩺 Ajouter suivi santé",
    "bandeDetail.registerConsumption": "🌾 Enregistrer consommation",
    "bandeDetail.sell": "🛒 Vendre",
    "bandeDetail.closeFlock": "🔒 Clôturer la bande",
    "bandeDetail.mortalityHistory": "Historique mortalité",
    "bandeDetail.record": "Enregistrer",
    "bandeDetail.noMortality": "Aucune mortalité enregistrée",
    "bandeDetail.unknownCause": "Cause inconnue",
    "bandeDetail.treatments": "Traitements sanitaires",
    "bandeDetail.addTreatment": "+ Ajouter traitement",
    "bandeDetail.noTreatment": "Aucun traitement enregistré",
    "bandeDetail.units": "{n} unités",
    "bandeDetail.reminder": "Rappel: {date}",
    "bandeDetail.feedConsumption": "Consommation provende",
    "bandeDetail.totalFeedCostRow": "Total coût provende",
    "bandeDetail.noConsumption": "Aucune consommation enregistrée",
    "bandeDetail.excel": "Excel",
    // Bande card
    "bande.card.statusActive": "En cours",
    "bande.card.statusSold": "Vendue",
    "bande.card.statusPlanned": "Planifiée",
    "bande.card.statusLost": "Perdue",
    "bande.card.deaths": "{n} morts",
    "bande.card.days": "{n} jours",
    "bande.card.enteredOn": "Entrée le {date}",
    "bande.card.mortality": "Enregistrer mortalité",
    // Bande form
    "bande.form.editTitle": "Modifier la bande",
    "bande.form.newTitle": "Nouvelle bande",
    "bande.form.name": "Nom de la bande",
    "bande.form.namePlaceholder": "Ex: Bande Mars 2026",
    "bande.form.species": "Espèce",
    "bande.form.strain": "Souche",
    "bande.form.strainManualPlaceholder": "Saisir la souche manuellement",
    "bande.form.strainPlaceholder": "Sélectionner une souche",
    "bande.form.strainManual": "✏️ Saisir manuellement",
    "bande.form.other": "Autre",
    "bande.form.initialCount": "Effectif initial",
    "bande.form.status": "Statut",
    "bande.form.exitDate": "Date de sortie",
    "bande.form.avgWeight": "Poids moyen (kg)",
    "bande.form.notesPlaceholder": "Notes supplémentaires...",
    "bande.form.saving": "Enregistrement...",
    // Medicament types and units
    "med.type.vaccin": "Vaccin",
    "med.type.antibiotique": "Antibiotique",
    "med.type.antiparasitaire": "Antiparasitaire",
    "med.type.vitamines": "Vitamines",
    "med.type.desinfectant": "Désinfectant",
    "med.type.autre": "Autre",
    "med.units.doses": "Doses",
    "med.units.ml": "ml",
    "med.units.g": "g",
    "med.units.kg": "kg",
    "med.units.flacons": "Flacons",
    "med.units.sachets": "Sachets",
    // Medicament card
    "med.stockLow": "Stock bas",
    "med.expiredOn": "Expiré le",
    "med.expiresOn": "Expire le",
    "med.expired": "Expiré",
    "med.soonBadge": "Bientôt",
    "med.boughtOn": "Acheté le",
    "med.supplierLabel": "Fournisseur: {name}",
    "med.archived": "Archivé",
    "med.registerTreatment": "Enregistrer traitement",
    "med.unarchive": "Désarchiver",
    "med.archive": "Archiver",
    // Medicament form
    "med.form.editTitle": "Modifier le médicament",
    "med.form.newTitle": "Nouveau médicament / vaccin",
    "med.form.name": "Nom",
    "med.form.namePlaceholder": "Ex: Vaccin Newcastle",
    "med.form.stockQuantity": "Quantité en stock",
    "med.form.unit": "Unité",
    "med.form.alertThreshold": "Seuil d'alerte",
    "med.form.unitPrice": "Prix unitaire (FCFA)",
    "med.form.purchaseDate": "Date d'achat",
    "med.form.expirationDate": "Date d'expiration",
    "med.form.supplier": "Fournisseur",
    "med.form.optional": "Optionnel",
    "med.form.saving": "Enregistrement...",
    "med.form.add": "Ajouter",
    // Report labels
    "report.name": "Nom",
    "report.species": "Espèce",
    "report.initialCount": "Effectif initial",
    "report.currentCount": "Effectif actuel",
    "report.entryDate": "Date entrée",
    "report.status": "Statut",
    "report.avgWeight": "Poids moyen (kg)",
    "report.informationSheet": "Informations",
    "report.mortalitySheet": "Mortalités",
    "report.feedSheet": "Provende",
    "report.treatmentsSheet": "Traitements sanitaires",
    "report.count": "Nombre",
    "report.cause": "Cause",
    "report.feed": "Aliment",
    "report.quantityKg": "Quantité (kg)",
    "report.costFcfa": "Coût (FCFA)",
    "report.medication": "Médicament",
    "report.reason": "Motif",
    "report.quantityUsed": "Qté utilisée",
    "report.reminder": "Rappel",
    // Charts (accounting & dashboard)
    "charts.expensesByCategory": "Dépenses par catégorie",
    "charts.revenueByCategory": "Revenus par catégorie",
    "charts.top5": "Top 5 dépenses",
    "charts.revenusDepensesJour": "Revenus & Dépenses par jour",
    "charts.revenusDepensesMois": "Revenus & Dépenses par mois",
    "charts.revenus": "Revenus",
    "charts.depenses": "Dépenses",
    // Rentabilité tab
    "rentabilite.netBenefit": "Bénéfice net estimé",
    "rentabilite.margin": "Marge",
    "rentabilite.revenus": "Revenus",
    "rentabilite.depenses": "Dépenses",
    "rentabilite.revenuParTete": "Revenu par tête",
    "rentabilite.coutParTete": "Coût par tête",
    "rentabilite.sujets": "{n} sujets",
    "rentabilite.toutesDepenses": "toutes dépenses",
    "rentabilite.margeBeneficiaire": "Marge bénéficiaire",
    "rentabilite.surVentes": "sur les ventes",
    "rentabilite.pasDeRevenus": "pas de revenus",
    "rentabilite.detailDepenses": "Détail des dépenses",
    "rentabilite.alimentation": "Alimentation (provende)",
    "rentabilite.medicamentsSoins": "Médicaments & soins",
    "rentabilite.achatPoussins": "Achat poussins",
    "rentabilite.autresCharges": "Autres charges",
    "rentabilite.totalDepenses": "Total dépenses",
    "rentabilite.pctDesDepenses": "{pct}% des dépenses",
    "rentabilite.aucunRevenuTitle": "💡 Aucun revenu enregistré",
    "rentabilite.aucunRevenuDesc": "Pour calculer la rentabilité complète, enregistrez vos ventes en ajoutant des transactions de type \"Revenu\" liées à cette bande dans la Comptabilité.",
    "common.saving": "Enregistrement...",
    // Mortalité form
    "mort.form.editTitle": "Modifier mortalité — {name}",
    "mort.form.newTitle": "Enregistrer mortalité — {name}",
    "mort.form.date": "Date",
    "mort.form.count": "Nombre de morts",
    "mort.form.cause": "Cause",
    "mort.cause.maladie": "Maladie",
    "mort.cause.chaleur": "Chaleur",
    "mort.cause.predateur": "Prédateur",
    "mort.cause.accident": "Accident",
    "mort.cause.inconnue": "Inconnue",
    "mort.form.notes": "Notes",
    "mort.form.actionEdit": "Modifier",
    "mort.form.actionNew": "Enregistrer",
    // Employé
    "emp.statut.actif": "Actif",
    "emp.statut.inactif": "Inactif",
    "emp.statut.conge": "En congé",
    "emp.poste.promoteur": "🌟 Promoteur",
    "emp.poste.eleveur": "🐔 Éleveur",
    "emp.poste.bascourier": "🚚 Bascourier",
    "emp.poste.veterinaire": "🩺 Vétérinaire",
    "emp.poste.technicien": "🔧 Technicien",
    "emp.poste.comptable": "📊 Comptable",
    "emp.poste.chauffeur": "🚗 Chauffeur",
    "emp.poste.gardien": "🛡️ Gardien",
    "emp.poste.autre": "👤 Autre",
    "emp.form.editTitle": "Modifier l'employé",
    "emp.form.newTitle": "Nouvel employé",
    "emp.form.fullName": "Nom complet",
    "emp.form.namePlaceholder": "Ex: Amadou Diallo",
    "emp.form.role": "Poste",
    "emp.form.phone": "Téléphone",
    "emp.form.phonePlaceholder": "+237 6XX XXX XXX",
    "emp.form.salary": "Salaire mensuel (FCFA)",
    "emp.form.salaryPlaceholder": "Ex: 80000",
    "emp.form.hireDate": "Date d'embauche",
    "emp.form.status": "Statut",
    "emp.form.notes": "Notes",
    "emp.form.notesPlaceholder": "Compétences, observations...",
    "emp.card.salaryMonth": "Salaire / mois",
    "emp.card.hiredOn": "Embauché le {date}",
    // Traitement form
    "trait.form.title": "Enregistrer un traitement sanitaire",
    "trait.form.bande": "Bande concernée",
    "trait.form.bandePlaceholder": "Sélectionner une bande",
    "trait.form.motif": "Motif",
    "trait.motif.vaccination": "Vaccination",
    "trait.motif.traitement_maladie": "Traitement maladie",
    "trait.motif.prevention": "Prévention",
    "trait.motif.deworming": "Déparasitage",
    "trait.motif.autre": "Autre",
    "trait.form.med": "Médicament utilisé",
    "trait.form.medPlaceholder": "Sélectionner",
    "trait.form.none": "Aucun",
    "trait.form.date": "Date du traitement",
    "trait.form.qty": "Quantité utilisée",
    "trait.form.qtyPlaceholder": "Optionnel",
    "trait.form.reminder": "Prochain rappel",
    "trait.form.notes": "Notes / observations",
    "trait.form.notesPlaceholder": "Observations, réactions, dosage...",
    // Consommation form
    "conso.form.title.default": "Consommation — Enregistrer consommation",
    "conso.form.title.stock": "Consommation — {stock}",
    "conso.form.currentStock": "Stock actuel: {n} kg",
    "conso.form.feed": "Aliment",
    "conso.form.feedPlaceholder": "Sélectionner un aliment",
    "conso.form.bande": "Bande",
    "conso.form.bandePlaceholder": "Sélectionner une bande",
    "conso.form.qty": "Quantité consommée (kg)",
    "conso.form.date": "Date",
    "conso.form.notes": "Notes",
    // Boutique
    "boutique.title": "Ma Boutique AgriVolaille",
    "boutique.description": "Vos annonces visibles par tous les acheteurs sur AgriVolaille Market",
    "boutique.newAd": "Nouvelle annonce",
    "boutique.editAd": "Modifier l'annonce",
    "boutique.product": "Produit",
    "boutique.product.oeufs": "🥚 Œufs",
    "boutique.product.poulet_chair": "🐔 Poulet chair",
    "boutique.product.autre": "📦 Autre",
    "boutique.titleLabel": "Titre *",
    "boutique.titlePlaceholder": "ex: Vente œufs frais",
    "boutique.descriptionLabel": "Description (optionnel)",
    "boutique.qtyLabel": "Quantité disponible *",
    "boutique.unit": "Unité",
    "boutique.unit.plateau": "Plateau",
    "boutique.unit.piece": "Pièce",
    "boutique.unit.kg": "Kg",
    "boutique.priceLabel": "Prix unitaire",
    "boutique.pricePlaceholder": "ex: 2500",
    "boutique.currency": "Devise",
    "boutique.city": "Ville",
    "boutique.country": "Pays",
    "boutique.whatsapp": "Numéro WhatsApp",
    "boutique.farmName": "Nom de la ferme",
    "boutique.preview": "Aperçu",
    "boutique.previewTitlePlaceholder": "Titre de l'annonce",
    "boutique.preview.farm": "Ferme",
    "boutique.preview.qtyAvailable": "Quantité disponible",
    "boutique.preview.unitPrice": "Prix unitaire",
    "boutique.publish": "Publier l'annonce",
    "boutique.verifiedFarm": "Ferme Vérifiée AgriVolaille",
    "boutique.empty.title": "Votre boutique est vide",
    "boutique.empty.desc": "Publiez votre première annonce pour être visible sur AgriVolaille Market",
    "boutique.menuEdit": "Modifier",
    "boutique.menuDelete": "Supprimer",
    "boutique.qtyShort": "Qté",
    "boutique.marketingVisual": "Visuel marketing",
    "boutique.share.title": "Partager",
    "boutique.share.withImage": "Partager (avec image)",
    "boutique.share.toFacebook": "Partager sur Facebook",
    "boutique.share.toWhatsApp": "Partager sur WhatsApp",
    "boutique.share.openTikTok": "Ouvrir TikTok",
    "boutique.share.copyText": "Copier le texte",
    "boutique.share.copyTextImage": "Copier le texte et l'image",
    "boutique.share.openTitle": "Ouverture de {name}",
    "boutique.share.imageCopied": "Le texte et l'image ont été copiés — collez-les (Ctrl/Cmd+V) dans votre message.",
    "boutique.share.textCopied": "Le texte a été copié — collez-le (Ctrl/Cmd+V) dans votre message.",
    "boutique.share.availableNow": "✅ Disponible immédiatement",
    "boutique.share.qtyAvailable": "✅ Quantité disponible : {n} {unit}",
    "boutique.share.pricePerUnit": "✅ Prix : {n} {devise} / {unit}",
    "boutique.share.fromFarm": "✅ Produit issu de la ferme {ferme}",
    "boutique.share.locationLabel": "📍 {lieu}",
    "boutique.share.contactWhatsApp": "📞 Contact WhatsApp : {wa}",
    "boutique.share.beforeStockout": "Profitez-en avant rupture de stock !",
    "boutique.share.viaApp": "Publié via AgriVolaille 🌾",
    "boutique.share.intro.oeufs": "🥚 ŒUFS FRAIS DISPONIBLES !",
    "boutique.share.intro.poulet_chair": "🐔 POULET CHAIR FRAIS DISPONIBLE !",
    "boutique.share.introDefault": "📦 {titre} !",
    "boutique.share.locationFallback": "Contactez-nous pour la localisation",
    // PDF report
    "rapport.popupBlocked": "Veuillez autoriser les popups pour générer le rapport.",
    "rapport.print": "🖨️ Imprimer / Enregistrer en PDF",
    "rapport.sheetTitle": "Rapport Mensuel — {period}",
    "rapport.generatedSubtitle": "AgriVolaille · Généré le {date}",
    "rapport.revenues": "Revenus",
    "rapport.expenses": "Dépenses",
    "rapport.netBalanceEmoji": "Solde net {emoji}",
    "rapport.mortalityLabel": "Mortalités",
    "rapport.mortalityRate": "Taux mortalité",
    "rapport.consumedFeed": "Aliments consommés",
    "rapport.activeBandes": "Bandes actives",
    "rapport.totalBandes": "Total bandes",
    "rapport.financialSummary": "Résumé financier",
    "rapport.indicatorLabel": "Indicateur",
    "rapport.amountLabel": "Montant",
    "rapport.totalRevenusLabel": "Revenus totaux",
    "rapport.totalDepensesLabel": "Dépenses totales",
    "rapport.netBalanceLabel": "Solde net",
    "rapport.txCountLabel": "Nombre de transactions",
    "rapport.expensesByCat": "Dépenses par catégorie",
    "rapport.revenuesByCat": "Revenus par catégorie",
    "rapport.categoryCol": "Catégorie",
    "rapport.amountFcfaCol": "Montant (FCFA)",
    "rapport.pctCol": "% du total",
    "rapport.total": "TOTAL",
    "rapport.allBandesTable": "Toutes les bandes",
    "rapport.nameCol": "Nom",
    "rapport.speciesCol": "Espèce",
    "rapport.countCol": "Effectif actuel",
    "rapport.statusCol": "Statut",
    "rapport.statusActive": "Active",
    "rapport.statusCompleted": "Terminée",
    "rapport.statusPlanned": "Planifiée",
    "rapport.noFlocks": "Aucune bande enregistrée",
    "rapport.footer": "AgriVolaille — Rapport généré le {date}",
    // Feed form
    "feed.form.editTitle": "Modifier l'aliment",
    "feed.form.newTitle": "Nouvel aliment",
    "feed.form.name": "Nom",
    "feed.form.namePlaceholder": "Ex: Poussinière",
    "feed.form.type": "Type",
    "feed.type.demarrage": "Démarrage",
    "feed.type.croissance": "Croissance",
    "feed.type.finition": "Finition",
    "feed.type.pondeuse": "Ponte",
    "feed.type.premix": "Prémix",
    "feed.type.autre": "Autre",
    "feed.form.quantity": "Quantité (kg)",
    "feed.form.alertThreshold": "Seuil d'alerte (kg)",
    "feed.form.pricePerKg": "Prix/kg (FCFA)",
    "feed.form.supplier": "Fournisseur",
    "feed.form.optional": "Optionnel",
    // Reappro form
    "reappro.title": "Réapprovisionnement — {name}",
    "reappro.currentStock": "Stock actuel : {n} kg",
    "reappro.date": "Date de réception *",
    "reappro.quantity": "Quantité ajoutée (kg) *",
    "reappro.quantityPlaceholder": "ex: 100",
    "reappro.pricePerKg": "Prix par kg (FCFA)",
    "reappro.pricePlaceholder": "ex: 350",
    "reappro.priceHint": "Laissez vide pour conserver le prix actuel",
    "reappro.supplier": "Fournisseur",
    "reappro.supplierPlaceholder": "Nom du fournisseur",
    "reappro.estimatedCost": "Coût estimé de cet achat",
    "reappro.submit": "Réapprovisionner",
    // Stock list item
    "stock.lastUpdate": "Dernière MAJ : {date}",
    "stock.reappro": "+ Réappro",
    "stock.consumption": "− Consommation",
    "stock.initialKg": "/ {n} kg seuil",
    // Assistant
    "assistant.title": "Assistant AgriVolaille",
    "assistant.description": "Optimisez la consommation alimentaire de vos bandes et posez toutes vos questions sur la ferme",
    "assistant.conversations": "Conversations",
    "assistant.myConversations": "Mes conversations",
    "assistant.greeting": "Bonjour {name} !",
    "assistant.intro": "Je peux analyser la consommation alimentaire de vos bandes (FCR, coûts, anomalies) et répondre à toute question sur votre ferme.",
    "assistant.thinking": "L'assistant réfléchit...",
    "assistant.placeholder": "Posez une question sur votre ferme...",
    "assistant.newConversation": "Nouvelle conversation",
    "assistant.suggestion.fcr": "Analyse la consommation alimentaire de ma bande active et calcule le FCR",
    "assistant.suggestion.anomalies": "Y a-t-il des anomalies dans la consommation d'aliment récemment ?",
    "assistant.suggestion.balance": "Quel est mon solde net ce mois-ci ?",
    "assistant.suggestion.lowStock": "Quels stocks sont en alerte basse ?",
    "assistant.deleteConfirm": "Supprimer cette conversation ? Cette action est irréversible.",
    "assistant.deleteTitle": "Conversation supprimée",
    "assistant.renameUnsupported": "Le renommage n'est pas supporté par le SDK",
    "assistant.deleteUnsupported": "La suppression n'est pas supportée par le SDK",
    "assistant.renameError": "Renommage impossible",
    "assistant.deleteError": "Suppression impossible",
    "assistant.createError": "Impossible de créer la conversation",
    "assistant.startError": "Impossible de démarrer la conversation",
  },
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.bandes": "Flocks",
    "nav.provenderie": "Feed Management",
    "nav.medicaments": "Medications",
    "nav.equipes": "Teams",
    "nav.comptabilite": "Accounting",
    "nav.fournisseurs": "Suppliers",
    "nav.clients": "Clients",
    "nav.boutique": "My Shop",
    "nav.assistant": "My Assistant",
    "nav.parametres": "Settings",
    "nav.logout": "Logout",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.more": "More",
    "nav.home": "Home",
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.description": "Overview of your poultry farm",
    "dashboard.period": "Financial statistics period",
    "dashboard.display": "Display",
    "dashboard.revenues": "Revenue",
    "dashboard.expenses": "Expenses",
    "dashboard.balance": "Net balance",
    "dashboard.mortality": "Total mortality",
    "dashboard.activeBands": "Active flocks",
    "dashboard.subjects": "subjects",
    // Common
    "common.add": "Add",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.search": "Search",
    "common.loading": "Loading...",
    "common.allMonths": "All months",
    "common.noData": "No data",
    "common.today": "Today",
    "common.yesterday": "Yesterday",
    "common.daysAgo": "{n} days ago",
    "common.kg": "kg",
    // Bandes
    "bandes.title": "My Flocks",
    "bandes.newBande": "New flock",
    "bandes.descOne": "{n} active flock",
    "bandes.descMany": "{n} active flocks",
    "bandes.totalActive": "Total active flocks",
    "bandes.monthMortality": "Total mortality this month",
    "bandes.monthFeedCost": "Total feed cost this month",
    "bandes.all": "All",
    "bandes.active": "In progress",
    "bandes.sold": "Sold",
    "bandes.planned": "Planned",
    "bandes.totalPlural": "{n} flocks in total",
    "bandes.totalSingular": "{n} flock in total",
    "bandes.empty.title": "No flocks",
    "bandes.empty.desc": "Start by adding your first poultry flock",
    "bandes.empty.action": "Add a flock",
    // Provenderie
    "provenderie.title": "Feed Management",
    "provenderie.descOne": "{n} feed item in stock",
    "provenderie.descMany": "{n} feed items in stock",
    "provenderie.newFood": "New feed item",
    "provenderie.totalValue": "Total stock value (FCFA)",
    "provenderie.lowAlerts": "Low stock alerts",
    "provenderie.monthConsumption": "Consumption this month (kg)",
    "provenderie.search": "Search by name...",
    "provenderie.filter.all": "All",
    "provenderie.filter.stock": "In stock",
    "provenderie.filter.alert": "Alert",
    "provenderie.filter.archived": "Archived",
    "provenderie.empty.title": "No feed in stock",
    "provenderie.empty.desc": "Add your feeds to track stock and consumption",
    "provenderie.empty.action": "Add a feed",
    "provenderie.history.title": "History",
    "provenderie.history.empty": "No consumption recorded",
    // Settings
    "settings.title": "Settings",
    "settings.description": "Manage your profile and account preferences",
    "settings.language": "Application language",
    "settings.languageDesc": "Choose the display language for the interface",
    "settings.french": "Français",
    "settings.english": "English",
    "settings.profile": "Personal information",
    "settings.profileDesc": "Your name and contact details",
    "settings.fullName": "Full name",
    "settings.fullNamePlaceholder": "Your full name",
    "settings.phone": "Phone number",
    "settings.email": "Email address",
    "settings.emailNote": "Email cannot be changed.",
    "settings.saveChanges": "Save changes",
    "settings.saving": "Saving...",
    "settings.saved": "Saved",
    "settings.password": "Change password",
    "settings.passwordDesc": "Update your login password",
    "settings.newPassword": "New password",
    "settings.confirmPassword": "Confirm new password",
    "settings.changePassword": "Change password",
    "settings.changing": "Changing...",
    "settings.account": "My account",
    "settings.accountDesc": "Account information and actions",
    "settings.memberSince": "Member since",
    "settings.role": "Role",
    "settings.admin": "Administrator",
    "settings.user": "User",
    "settings.adminDesc": "Application administrator",
    "settings.userDesc": "Standard user",
    "settings.logout": "Log out",
    "settings.active": "Active",
    "settings.genericError": "An error occurred while changing your password.",
    "settings.toastTitle": "Profile updated",
    "settings.toastDesc": "Your information has been saved.",
    "settings.pwToastTitle": "Password changed",
    "settings.pwToastDesc": "Your password has been updated successfully.",
    "settings.pwMismatch": "Passwords do not match.",
    "settings.pwTooShort": "New password must be at least 6 characters.",
    "settings.pwPlaceholder": "Minimum 6 characters",
    "settings.deleteAccount": "Delete my account",
    "settings.deleteConfirmTitle": "Permanently delete your account?",
    "settings.deleteConfirmDesc": "⚠️ Warning: Deleting your account will permanently erase all your data, records, files, settings, and history from the platform. This action cannot be undone. Do you really want to continue?",
    "settings.deleteBackupNote": "💡 Before proceeding, you may export a backup of your data from the Flocks and Accounting pages.",
    "settings.deleteAcknowledgeLabel": "I understand this action is permanent and cannot be undone.",
    "settings.deleteConfirmButton": "Yes, delete my account",
    "settings.deleteEmailSubject": "AgriVolaille account deletion request",
    "settings.deleteEmailBody": "A deletion request for the account associated with {email} has been submitted. Your account and all associated data will be deleted shortly.",
    "settings.deleteSubmittedTitle": "Request sent",
    "settings.deleteSubmittedDesc": "Your deletion request has been recorded. You will now be logged out.",
    // Common additional
    "common.update": "Update",
    "common.create": "Create",
    "common.nameRequired": "Name *",
    "common.phone": "Phone",
    "common.address": "Address",
    "common.notes": "Notes",
    // Equipes
    "equipes.title": "Teams",
    "equipes.description": "Manage your employees and track payroll",
    "equipes.newEmploye": "New employee",
    "equipes.activeEmployees": "Active employees",
    "equipes.payrollPerMonth": "Monthly payroll",
    "equipes.inactiveOrLeave": "Inactive / on leave",
    "equipes.empty.title": "No employees",
    "equipes.empty.desc": "Add your employees to track your team and payroll",
    "equipes.empty.action": "Add an employee",
    // Fournisseurs
    "fournisseurs.title": "Suppliers",
    "fournisseurs.descOne": "{n} supplier",
    "fournisseurs.descMany": "{n} suppliers",
    "fournisseurs.newSupplier": "New supplier",
    "fournisseurs.search": "Search...",
    "fournisseurs.empty.title": "No supplier",
    "fournisseurs.empty.desc": "Add your suppliers to find them easily",
    "fournisseurs.empty.action": "Add",
    "fournisseurs.menu.edit": "Edit",
    "fournisseurs.menu.delete": "Delete",
    "fournisseurs.form.editTitle": "Edit supplier",
    "fournisseurs.form.newTitle": "New supplier",
    // Clients
    "clients.title": "Clients",
    "clients.descOne": "{n} client",
    "clients.descMany": "{n} clients",
    "clients.newClient": "New client",
    "clients.search": "Search...",
    "clients.empty.title": "No clients",
    "clients.empty.desc": "Add your clients to find them easily",
    "clients.empty.action": "Add",
    "clients.menu.edit": "Edit",
    "clients.menu.delete": "Delete",
    "clients.form.editTitle": "Edit client",
    "clients.form.newTitle": "New client",
    // Common additional
    "common.revenus": "Revenue",
    "common.depenses": "Expenses",
    "common.balanceShort": "Balance",
    "common.viewAll": "View all",
    "common.noTransaction": "No transactions",
    "common.noActiveBands": "No active flocks",
    "common.noFeedRecorded": "No feed recorded",
    // Charts
    "dashboard.charts.headerTitle": "Revenue vs Expenses",
    "dashboard.charts.lastMonths": "Last {n} months",
    "dashboard.charts.balance": "Balance",
    "dashboard.charts.monthsN": "{n} months",
    "dashboard.charts.expByCat": "Expenses by category",
    "dashboard.charts.revByCat": "Revenue by category",
    "dashboard.charts.top5": "Top 5 expenses this month",
    "dashboard.charts.noExpense": "No expenses this month",
    "dashboard.recentTx": "Recent transactions",
    "dashboard.activeBandsHeading": "Active flocks",
    "dashboard.stockAlerts": "Stock alerts",
    "dashboard.kgRemaining": "{actual} kg left (threshold: {threshold} kg)",
    "dashboard.allStocksOk": "All stocks are OK",
    // Period filter
    "periodFilter.mode": "Period mode",
    "periodFilter.singleMonth": "Single month",
    "periodFilter.range": "Custom range",
    "periodFilter.month": "Month",
    "periodFilter.from": "From",
    "periodFilter.to": "To",
    "periodFilter.startMonthPlaceholder": "Start month",
    "periodFilter.endMonthPlaceholder": "End month",
    // Species
    "espece.poulet_chair": "Broiler",
    "espece.pondeuse": "Layer",
    "espece.pintade": "Guinea fowl",
    "espece.canard": "Duck",
    "espece.dinde": "Turkey",
    "espece.caille": "Quail",
    // Categories
    "cat.vente_volaille": "Poultry sale",
    "cat.vente_oeufs": "Egg sale",
    "cat.vente_fumier": "Manure sale",
    "cat.achat_aliment": "Feed purchase",
    "cat.achat_poussins": "Chick purchase",
    "cat.medicaments": "Medications",
    "cat.main_oeuvre": "Labor",
    "cat.equipement": "Equipment",
    "cat.transport": "Transport",
    "cat.electricite_eau": "Electricity/Water",
    "cat.autre": "Other",
    // Medicaments
    "medicaments.title": "Medications & Health",
    "medicaments.description": "Manage your health supplies and treatment history",
    "medicaments.newMedicament": "New medication",
    "medicaments.inStock": "Products in stock",
    "medicaments.lowStockAlerts": "Low stock alerts",
    "medicaments.upcomingReminders": "Upcoming reminders",
    "medicaments.tabs.stock": "Medication stock",
    "medicaments.tabs.history": "Treatment history",
    "medicaments.tabs.calendar": "📅 Calendar",
    "medicaments.tabs.archived": "Archived",
    "medicaments.empty.title": "No medication",
    "medicaments.empty.desc": "Add your medications and vaccines to track stock and treatments",
    "medicaments.empty.action": "Add a medication",
    "medicaments.archive.empty": "No archived medications",
    "medicaments.unknownMed": "Unknown medication",
    "medicaments.reminders.empty": "No upcoming reminders",
    "medicaments.reminders.emptyDesc": "Add a treatment with a reminder date to see it here",
    "medicaments.reminders.add": "Add a reminder",
    "medicaments.selectBande": "Select a flock",
    "medicaments.daysLeftOne": "In {n} day",
    "medicaments.daysLeftMany": "In {n} days",
    // Comptabilite
    "comptabilite.title": "Accounting",
    "comptabilite.exercice": "Period {period}",
    "comptabilite.excel": "Excel",
    "comptabilite.csv": "CSV",
    "comptabilite.pdfReport": "PDF report",
    "comptabilite.newTransaction": "New transaction",
    "comptabilite.revenues": "Revenue for the period",
    "comptabilite.expenses": "Expenses for the period",
    "comptabilite.netBalance": "Net balance",
    "comptabilite.txCount": "Number of transactions",
    "comptabilite.filter.type": "Type",
    "comptabilite.filter.category": "Category",
    "comptabilite.filter.band": "Flock",
    "comptabilite.filter.search": "Search",
    "comptabilite.filter.searchPlaceholder": "Keywords...",
    "comptabilite.filter.allTypes": "All",
    "comptabilite.filter.income": "Revenue",
    "comptabilite.filter.expense": "Expenses",
    "comptabilite.filter.allCategories": "All",
    "comptabilite.filter.allBands": "All flocks",
    "comptabilite.empty.title": "No transactions",
    "comptabilite.empty.desc": "Record your income and expenses to see data",
    "comptabilite.empty.action": "Add a transaction",
    "common.heads": "heads",
    "common.add": "Add",
    // Bande detail page
    "bandeDetail.title": "Flock details",
    "bandeDetail.notFound": "Flock not found",
    "bandeDetail.backToFlocks": "Back to flocks",
    "bandeDetail.strain": "Strain",
    "bandeDetail.strainUndefined": "Not defined",
    "bandeDetail.species": "Species",
    "bandeDetail.statusActive": "In progress",
    "bandeDetail.statusCompleted": "Completed",
    "bandeDetail.statusPlanned": "Planned",
    "bandeDetail.headsCurInit": "Current / initial heads",
    "bandeDetail.deaths": "{n} deaths",
    "bandeDetail.totalMortality": "Total mortality",
    "bandeDetail.totalFeedCost": "Total feed cost",
    "bandeDetail.costPerHead": "Production cost per head",
    "bandeDetail.rearingDuration": "Rearing duration",
    "bandeDetail.days": "{n} days",
    "bandeDetail.growthCurveTitle": "Growth curve",
    "bandeDetail.slaughterBadge": "Slaughter D42",
    "bandeDetail.noRealRecord": "0 real record",
    "bandeDetail.slaughterLabel": "Slaughter",
    "bandeDetail.reference": "Reference",
    "bandeDetail.real": "Actual",
    "bandeDetail.icTarget": "Target FCR: 1.8 - 2.2",
    "bandeDetail.mortalityTarget": "Target mortality: < 3%",
    "bandeDetail.startLabel": "Start: {date}",
    "bandeDetail.daysAxis": "Days / Days",
    "bandeDetail.tabOverview": "Overview",
    "bandeDetail.tabHealth": "Health",
    "bandeDetail.tabMortality": "Mortality",
    "bandeDetail.tabFeed": "Feed",
    "bandeDetail.tabProfitability": "Profitability",
    "bandeDetail.infoSection": "Flock information",
    "bandeDetail.entryDate": "Entry date",
    "bandeDetail.avgEntryWeight": "Average entry weight",
    "bandeDetail.lastHealthFollowups": "Latest health follow-ups",
    "bandeDetail.noFollowup": "No follow-up.",
    "bandeDetail.registerMortality": "🔴 Record mortality",
    "bandeDetail.addHealthFollowup": "🩺 Add health follow-up",
    "bandeDetail.registerConsumption": "🌾 Record consumption",
    "bandeDetail.sell": "🛒 Sell",
    "bandeDetail.closeFlock": "🔒 Close flock",
    "bandeDetail.mortalityHistory": "Mortality history",
    "bandeDetail.record": "Record",
    "bandeDetail.noMortality": "No mortality recorded",
    "bandeDetail.unknownCause": "Unknown cause",
    "bandeDetail.treatments": "Health treatments",
    "bandeDetail.addTreatment": "+ Add treatment",
    "bandeDetail.noTreatment": "No treatment recorded",
    "bandeDetail.units": "{n} units",
    "bandeDetail.reminder": "Reminder: {date}",
    "bandeDetail.feedConsumption": "Feed consumption",
    "bandeDetail.totalFeedCostRow": "Total feed cost",
    "bandeDetail.noConsumption": "No consumption recorded",
    "bandeDetail.excel": "Excel",
    // Bande card
    "bande.card.statusActive": "In progress",
    "bande.card.statusSold": "Sold",
    "bande.card.statusPlanned": "Planned",
    "bande.card.statusLost": "Lost",
    "bande.card.deaths": "{n} deaths",
    "bande.card.days": "{n} days",
    "bande.card.enteredOn": "Entered on {date}",
    "bande.card.mortality": "Record mortality",
    // Bande form
    "bande.form.editTitle": "Edit flock",
    "bande.form.newTitle": "New flock",
    "bande.form.name": "Flock name",
    "bande.form.namePlaceholder": "E.g. Flock March 2026",
    "bande.form.species": "Species",
    "bande.form.strain": "Strain",
    "bande.form.strainManualPlaceholder": "Enter strain manually",
    "bande.form.strainPlaceholder": "Select a strain",
    "bande.form.strainManual": "✏️ Enter manually",
    "bande.form.other": "Other",
    "bande.form.initialCount": "Initial count",
    "bande.form.status": "Status",
    "bande.form.exitDate": "Exit date",
    "bande.form.avgWeight": "Average weight (kg)",
    "bande.form.notesPlaceholder": "Additional notes...",
    "bande.form.saving": "Saving...",
    // Medicament types and units
    "med.type.vaccin": "Vaccine",
    "med.type.antibiotique": "Antibiotic",
    "med.type.antiparasitaire": "Antiparasitic",
    "med.type.vitamines": "Vitamins",
    "med.type.desinfectant": "Disinfectant",
    "med.type.autre": "Other",
    "med.units.doses": "Doses",
    "med.units.ml": "ml",
    "med.units.g": "g",
    "med.units.kg": "kg",
    "med.units.flacons": "Vials",
    "med.units.sachets": "Sachets",
    // Medicament card
    "med.stockLow": "Low stock",
    "med.expiredOn": "Expired on",
    "med.expiresOn": "Expires on",
    "med.expired": "Expired",
    "med.soonBadge": "Soon",
    "med.boughtOn": "Purchased on",
    "med.supplierLabel": "Supplier: {name}",
    "med.archived": "Archived",
    "med.registerTreatment": "Record treatment",
    "med.unarchive": "Unarchive",
    "med.archive": "Archive",
    // Medicament form
    "med.form.editTitle": "Edit medication",
    "med.form.newTitle": "New medication / vaccine",
    "med.form.name": "Name",
    "med.form.namePlaceholder": "E.g. Newcastle vaccine",
    "med.form.stockQuantity": "Stock quantity",
    "med.form.unit": "Unit",
    "med.form.alertThreshold": "Alert threshold",
    "med.form.unitPrice": "Unit price (FCFA)",
    "med.form.purchaseDate": "Purchase date",
    "med.form.expirationDate": "Expiration date",
    "med.form.supplier": "Supplier",
    "med.form.optional": "Optional",
    "med.form.saving": "Saving...",
    "med.form.add": "Add",
    // Report labels
    "report.name": "Name",
    "report.species": "Species",
    "report.initialCount": "Initial count",
    "report.currentCount": "Current count",
    "report.entryDate": "Entry date",
    "report.status": "Status",
    "report.avgWeight": "Average weight (kg)",
    "report.informationSheet": "Information",
    "report.mortalitySheet": "Mortality",
    "report.feedSheet": "Feed",
    "report.treatmentsSheet": "Health treatments",
    "report.count": "Count",
    "report.cause": "Cause",
    "report.feed": "Feed",
    "report.quantityKg": "Quantity (kg)",
    "report.costFcfa": "Cost (FCFA)",
    "report.medication": "Medication",
    "report.reason": "Reason",
    "report.quantityUsed": "Used quantity",
    "report.reminder": "Reminder",
    // Charts (accounting & dashboard)
    "charts.expensesByCategory": "Expenses by category",
    "charts.revenueByCategory": "Revenue by category",
    "charts.top5": "Top 5 expenses",
    "charts.revenusDepensesJour": "Revenue & Expenses by day",
    "charts.revenusDepensesMois": "Revenue & Expenses by month",
    "charts.revenus": "Revenue",
    "charts.depenses": "Expenses",
    // Rentabilité tab
    "rentabilite.netBenefit": "Estimated net profit",
    "rentabilite.margin": "Margin",
    "rentabilite.revenus": "Revenue",
    "rentabilite.depenses": "Expenses",
    "rentabilite.revenuParTete": "Revenue per head",
    "rentabilite.coutParTete": "Cost per head",
    "rentabilite.sujets": "{n} subjects",
    "rentabilite.toutesDepenses": "all expenses",
    "rentabilite.margeBeneficiaire": "Profit margin",
    "rentabilite.surVentes": "on sales",
    "rentabilite.pasDeRevenus": "no revenue",
    "rentabilite.detailDepenses": "Expense detail",
    "rentabilite.alimentation": "Feed",
    "rentabilite.medicamentsSoins": "Medications & care",
    "rentabilite.achatPoussins": "Chick purchase",
    "rentabilite.autresCharges": "Other charges",
    "rentabilite.totalDepenses": "Total expenses",
    "rentabilite.pctDesDepenses": "{pct}% of expenses",
    "rentabilite.aucunRevenuTitle": "💡 No revenue recorded",
    "rentabilite.aucunRevenuDesc": "To calculate full profitability, record your sales by adding revenue transactions linked to this flock in Accounting.",
    "common.saving": "Saving...",
    // Mortality form
    "mort.form.editTitle": "Edit mortality — {name}",
    "mort.form.newTitle": "Record mortality — {name}",
    "mort.form.date": "Date",
    "mort.form.count": "Number of deaths",
    "mort.form.cause": "Cause",
    "mort.cause.maladie": "Disease",
    "mort.cause.chaleur": "Heat",
    "mort.cause.predateur": "Predator",
    "mort.cause.accident": "Accident",
    "mort.cause.inconnue": "Unknown",
    "mort.form.notes": "Notes",
    "mort.form.actionEdit": "Edit",
    "mort.form.actionNew": "Record",
    // Employee
    "emp.statut.actif": "Active",
    "emp.statut.inactif": "Inactive",
    "emp.statut.conge": "On leave",
    "emp.poste.promoteur": "🌟 Promoter",
    "emp.poste.eleveur": "🐔 Breeder",
    "emp.poste.bascourier": "🚚 Courier",
    "emp.poste.veterinaire": "🩺 Veterinarian",
    "emp.poste.technicien": "🔧 Technician",
    "emp.poste.comptable": "📊 Accountant",
    "emp.poste.chauffeur": "🚗 Driver",
    "emp.poste.gardien": "🛡️ Guard",
    "emp.poste.autre": "👤 Other",
    "emp.form.editTitle": "Edit employee",
    "emp.form.newTitle": "New employee",
    "emp.form.fullName": "Full name",
    "emp.form.namePlaceholder": "E.g. Amadou Diallo",
    "emp.form.role": "Role",
    "emp.form.phone": "Phone",
    "emp.form.phonePlaceholder": "+237 6XX XXX XXX",
    "emp.form.salary": "Monthly salary (FCFA)",
    "emp.form.salaryPlaceholder": "E.g. 80000",
    "emp.form.hireDate": "Hire date",
    "emp.form.status": "Status",
    "emp.form.notes": "Notes",
    "emp.form.notesPlaceholder": "Skills, observations...",
    "emp.card.salaryMonth": "Salary/month",
    "emp.card.hiredOn": "Hired on {date}",
    // Traitement form
    "trait.form.title": "Record a health treatment",
    "trait.form.bande": "Flock concerned",
    "trait.form.bandePlaceholder": "Select a flock",
    "trait.form.motif": "Reason",
    "trait.motif.vaccination": "Vaccination",
    "trait.motif.traitement_maladie": "Disease treatment",
    "trait.motif.prevention": "Prevention",
    "trait.motif.deworming": "Deworming",
    "trait.motif.autre": "Other",
    "trait.form.med": "Medication used",
    "trait.form.medPlaceholder": "Select",
    "trait.form.none": "None",
    "trait.form.date": "Treatment date",
    "trait.form.qty": "Used quantity",
    "trait.form.qtyPlaceholder": "Optional",
    "trait.form.reminder": "Next reminder",
    "trait.form.notes": "Notes / observations",
    "trait.form.notesPlaceholder": "Observations, reactions, dosage...",
    // Consumption form
    "conso.form.title.default": "Consumption — Record consumption",
    "conso.form.title.stock": "Consumption — {stock}",
    "conso.form.currentStock": "Current stock: {n} kg",
    "conso.form.feed": "Feed",
    "conso.form.feedPlaceholder": "Select a feed",
    "conso.form.bande": "Flock",
    "conso.form.bandePlaceholder": "Select a flock",
    "conso.form.qty": "Consumed quantity (kg)",
    "conso.form.date": "Date",
    "conso.form.notes": "Notes",
    // Boutique
    "boutique.title": "My AgriVolaille Shop",
    "boutique.description": "Your listings visible to all buyers on AgriVolaille Market",
    "boutique.newAd": "New listing",
    "boutique.editAd": "Edit listing",
    "boutique.product": "Product",
    "boutique.product.oeufs": "🥚 Eggs",
    "boutique.product.poulet_chair": "🐔 Broiler",
    "boutique.product.autre": "📦 Other",
    "boutique.titleLabel": "Title *",
    "boutique.titlePlaceholder": "e.g. Fresh eggs for sale",
    "boutique.descriptionLabel": "Description (optional)",
    "boutique.qtyLabel": "Available quantity *",
    "boutique.unit": "Unit",
    "boutique.unit.plateau": "Tray",
    "boutique.unit.piece": "Piece",
    "boutique.unit.kg": "Kg",
    "boutique.priceLabel": "Unit price",
    "boutique.pricePlaceholder": "e.g. 2500",
    "boutique.currency": "Currency",
    "boutique.city": "City",
    "boutique.country": "Country",
    "boutique.whatsapp": "WhatsApp number",
    "boutique.farmName": "Farm name",
    "boutique.preview": "Preview",
    "boutique.previewTitlePlaceholder": "Listing title",
    "boutique.preview.farm": "Farm",
    "boutique.preview.qtyAvailable": "Available quantity",
    "boutique.preview.unitPrice": "Unit price",
    "boutique.publish": "Publish listing",
    "boutique.verifiedFarm": "AgriVolaille Verified Farm",
    "boutique.empty.title": "Your shop is empty",
    "boutique.empty.desc": "Publish your first listing to be visible on AgriVolaille Market",
    "boutique.menuEdit": "Edit",
    "boutique.menuDelete": "Delete",
    "boutique.qtyShort": "Qty",
    "boutique.marketingVisual": "Marketing visual",
    "boutique.share.title": "Share",
    "boutique.share.withImage": "Share (with image)",
    "boutique.share.toFacebook": "Share on Facebook",
    "boutique.share.toWhatsApp": "Share on WhatsApp",
    "boutique.share.openTikTok": "Open TikTok",
    "boutique.share.copyText": "Copy text",
    "boutique.share.copyTextImage": "Copy text and image",
    "boutique.share.openTitle": "Opening {name}",
    "boutique.share.imageCopied": "Text and image have been copied — paste (Ctrl/Cmd+V) into your message.",
    "boutique.share.textCopied": "Text has been copied — paste (Ctrl/Cmd+V) into your message.",
    "boutique.share.availableNow": "✅ Available immediately",
    "boutique.share.qtyAvailable": "✅ Available quantity: {n} {unit}",
    "boutique.share.pricePerUnit": "✅ Price: {n} {devise} / {unit}",
    "boutique.share.fromFarm": "✅ Product from farm {ferme}",
    "boutique.share.locationLabel": "📍 {lieu}",
    "boutique.share.contactWhatsApp": "📞 WhatsApp contact: {wa}",
    "boutique.share.beforeStockout": "Hurry, before stock runs out!",
    "boutique.share.viaApp": "Published via AgriVolaille 🌾",
    "boutique.share.intro.oeufs": "🥚 FRESH EGGS AVAILABLE!",
    "boutique.share.intro.poulet_chair": "🐔 FRESH BROILER AVAILABLE!",
    "boutique.share.introDefault": "📦 {titre}!",
    "boutique.share.locationFallback": "Contact us for location",
    // PDF report
    "rapport.popupBlocked": "Please allow pop-ups to generate the report.",
    "rapport.print": "🖨️ Print / Save as PDF",
    "rapport.sheetTitle": "Monthly Report — {period}",
    "rapport.generatedSubtitle": "AgriVolaille · Generated on {date}",
    "rapport.revenues": "Revenue",
    "rapport.expenses": "Expenses",
    "rapport.netBalanceEmoji": "Net balance {emoji}",
    "rapport.mortalityLabel": "Mortalities",
    "rapport.mortalityRate": "Mortality rate",
    "rapport.consumedFeed": "Feed consumed",
    "rapport.activeBandes": "Active flocks",
    "rapport.totalBandes": "Total flocks",
    "rapport.financialSummary": "Financial summary",
    "rapport.indicatorLabel": "Indicator",
    "rapport.amountLabel": "Amount",
    "rapport.totalRevenusLabel": "Total revenue",
    "rapport.totalDepensesLabel": "Total expenses",
    "rapport.netBalanceLabel": "Net balance",
    "rapport.txCountLabel": "Number of transactions",
    "rapport.expensesByCat": "Expenses by category",
    "rapport.revenuesByCat": "Revenue by category",
    "rapport.categoryCol": "Category",
    "rapport.amountFcfaCol": "Amount (FCFA)",
    "rapport.pctCol": "% of total",
    "rapport.total": "TOTAL",
    "rapport.allBandesTable": "All flocks",
    "rapport.nameCol": "Name",
    "rapport.speciesCol": "Species",
    "rapport.countCol": "Current count",
    "rapport.statusCol": "Status",
    "rapport.statusActive": "Active",
    "rapport.statusCompleted": "Completed",
    "rapport.statusPlanned": "Planned",
    "rapport.noFlocks": "No flocks recorded",
    "rapport.footer": "AgriVolaille — Report generated on {date}",
    // Feed form
    "feed.form.editTitle": "Edit feed",
    "feed.form.newTitle": "New feed",
    "feed.form.name": "Name",
    "feed.form.namePlaceholder": "E.g. Starter feed",
    "feed.form.type": "Type",
    "feed.type.demarrage": "Starter",
    "feed.type.croissance": "Grower",
    "feed.type.finition": "Finisher",
    "feed.type.pondeuse": "Layer",
    "feed.type.premix": "Premix",
    "feed.type.autre": "Other",
    "feed.form.quantity": "Quantity (kg)",
    "feed.form.alertThreshold": "Alert threshold (kg)",
    "feed.form.pricePerKg": "Price/kg (FCFA)",
    "feed.form.supplier": "Supplier",
    "feed.form.optional": "Optional",
    // Reappro form
    "reappro.title": "Restock — {name}",
    "reappro.currentStock": "Current stock: {n} kg",
    "reappro.date": "Reception date *",
    "reappro.quantity": "Added quantity (kg) *",
    "reappro.quantityPlaceholder": "e.g. 100",
    "reappro.pricePerKg": "Price per kg (FCFA)",
    "reappro.pricePlaceholder": "e.g. 350",
    "reappro.priceHint": "Leave empty to keep current price",
    "reappro.supplier": "Supplier",
    "reappro.supplierPlaceholder": "Supplier name",
    "reappro.estimatedCost": "Estimated cost of this purchase",
    "reappro.submit": "Restock",
    // Stock list item
    "stock.lastUpdate": "Last update: {date}",
    "stock.reappro": "+ Restock",
    "stock.consumption": "− Consumption",
    "stock.initialKg": "/ {n} kg threshold",
    // Assistant
    "assistant.title": "AgriVolaille Assistant",
    "assistant.description": "Optimize your flocks' feed consumption and ask any question about your farm",
    "assistant.conversations": "Conversations",
    "assistant.myConversations": "My conversations",
    "assistant.greeting": "Hello {name}!",
    "assistant.intro": "I can analyze your flocks' feed consumption (FCR, costs, anomalies) and answer any question about your farm.",
    "assistant.thinking": "The assistant is thinking...",
    "assistant.placeholder": "Ask a question about your farm...",
    "assistant.newConversation": "New conversation",
    "assistant.suggestion.fcr": "Analyze my active flock's feed consumption and calculate FCR",
    "assistant.suggestion.anomalies": "Are there any anomalies in feed consumption recently?",
    "assistant.suggestion.balance": "What is my net balance this month?",
    "assistant.suggestion.lowStock": "Which stocks are low on alert?",
    "assistant.deleteConfirm": "Delete this conversation? This action is irreversible.",
    "assistant.deleteTitle": "Conversation deleted",
    "assistant.renameUnsupported": "Renaming is not supported by the SDK",
    "assistant.deleteUnsupported": "Deletion is not supported by the SDK",
    "assistant.renameError": "Rename failed",
    "assistant.deleteError": "Delete failed",
    "assistant.createError": "Unable to create conversation",
    "assistant.startError": "Unable to start conversation",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("agrivolaille_lang") || "fr");

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem("agrivolaille_lang", newLang);
  };

  const t = (key, params) => {
    let str = translations[lang]?.[key] ?? translations["fr"]?.[key] ?? key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        str = String(str).replace(new RegExp(`\\{${k}\\}`, "g"), v);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}